version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./tools/Dockerfile
      args:
        CI: ${CI}
    restart: unless-stopped
    env_file: .env

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./tools/default.conf:/etc/nginx/conf.d/default.conf
