version: "3"

services:
    app:
        build:
            context: .
            dockerfile: tools/Dockerfile
        restart: unless-stopped
        env_file: ${GITHUB_ENV:-.env}

    nginx:
        image: nginx:1.17-alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./tools/default.conf:/etc/nginx/conf.d/default.conf
