name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: copy .env
        run: cp .env.example .env

      - name: Build
        run: docker-compose build

      - name: Deploy
        run: docker-compose up -d

      - name: "Stable test waiting ~30s"
        run: echo "$(date) Stable test waiting ~1 min" && sleep 30

      - run: docker-compose ps

      - run: curl localhost:80

      - id: result
        run: |
          running="$(docker-compose ps --services --filter "status=running")"
          services="$(docker-compose ps --services)"
          if [ "$running" != "$services" ]; then
              echo "Following services are not running:" 
              # Bash specific
              comm -13 <(sort <<<"$running") <(sort <<<"$services")
              exit 1
          else
              echo "All services are running"
              exit 0
          fi

      - if: ${{ always() }}
        run: docker-compose down
