name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Deploy
        uses: okteto/okteto:1.13.4
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
        run: okteto namespace && okteto stack deploy
