name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Deploy
        uses: okteto/okteto:1.13.4
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
        run: |
          echo $ENV_FILE > .env && \
          okteto namespace && \
          okteto stack deploy
