name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./tools/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Deploy
        env:
          APP_KEY_TEST: ${{ secrets.APP_KEY_TEST }}
          JWT_SECRET_TEST: ${{ secrets.JWT_SECRET_TEST }}
        run: docker-compose up -d

      - name: "Stable test waiting ~30s"
        run: sleep 30

      - run: docker-compose ps

      - run: curl localhost:80

      - id: result
        run: |
          running="$(docker-compose ps --services --filter "status=running")"
          services="$(docker-compose ps --services)"
          if [ "$running" != "$services" ]; then
              echo "Following services are not running:" 
              # Bash specific
              comm -13 <(sort <<<"$running") <(sort <<<"$services")
              exit 1
          else
              echo "All services are running"
              exit 0
          fi

      - if: ${{ always() }}
        run: docker-compose down
